plugins {
  id "java-library"
  id "org.owasp.dependencycheck" version "12.1.3"
}

dependencies {
}

dependencyCheck  {
  nvd.apiKey=System.getenv("NVD_API_KEY")
  nvd.datafeedUrl=project.findProperty('nvdDatafeedUrl')

  analyzers.assemblyEnabled=false
  analyzers.kev.url=project.findProperty('dependencyCheckKnownExploitedURL')
  data.directory=project.findProperty('dependencyCheckDirectory')
}
