# This is a regular build that will fetch the data returned by https://services.nvd.nist.gov/rest/json/cves/2.0 and saved it to this project
# This will allows other prrojects to use this data

name: Mirror NVD CVEs JSON

on:
  schedule:
    - cron: 0 */4 * * * # Every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
    - name: Get Gradle Dependency Check CVE Data
      #./gradlew -Dorg.gradle.jvmargs=-Xmx1g -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon --stacktrace --debug dependencyCheckUpdate -PnvdDatafeedUrl='https://raw.githubusercontent.com/interlok-tooling/nvd-cves-mirror/nvd-cache/nvd_api_cache/'
      run: |
        ./gradlew -Dorg.gradle.jvmargs=-Xmx1g -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon dependencyCheckPurge
        ./gradlew -Dorg.gradle.jvmargs=-Xmx1g -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon --stacktrace dependencyCheckAnalyze -PdependencyCheckAutoUpdate=false -PnvdDatafeedUrl='https://raw.githubusercontent.com/interlok-tooling/nvd-cves-mirror/nvd-cache/nvd_api_cache/'
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}  
    - name: Update CVE Data
      run: |
        gh release upload regular '/home/runner/.gradle/dependency-check-data/9.0/*' --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
